projects:
  cdk-bookmark-appsync-api:
    schemaPath: src/graphql/schema.json
    includes:
      - ''
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-2
        apiId: gec2vgu2orce5pkpdej45zlehm
        maxDepth: 2
